### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [ikenami/Svart-App#1]
I get errors in file ImageMap.cs...

public ImageMap (string fileName, string filePath, Bitmap bitmap)
        {
          _fileName = fileName;
            _filePath = filePath;
            _bitmap = bitmap;
        }

??

**Comment by 15w34r0n3D4y** [comment]
I fix it with 

public ImageMap (string fileName, string filePath, Bitmap bitmap)**: this()**

and now I can run application (get screenshot and keylog in folder) but nothing received on mail...

**Comment by ikenami** [comment]
That's weird. I don't get any error with ImageMap.cs.

For now, it will only send the files via mail after taking at least 5 screenshots.

If you are trying to send it with a different mail (not the one set in code), make sure that you are using the right smtp host and credentials (username and password). And that the mail security is set so it can be accessed by non-secure applications.

**Comment by 15w34r0n3D4y** [comment]
Yup, I get error when run, but fix it with : this()

**For now, it will only send the files via mail after taking at least 5 screenshots.**

That's the problem, upss, now it works! Thank you :)
